name: Update Clash Config

on:
  schedule:
    - cron: '0 * * * *'  # هر ساعت
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pyyaml
      - name: Run script
        run: python fetch_and_build_clash.py
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add ProjectAinita_Clash.yaml
          git commit -m 'Auto update Clash config' || echo "No changes to commit"
          git push
